// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://schavunumcsmnowthaoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjaGF2dW51bWNzbW5vd3RoYW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzMyNzksImV4cCI6MjA2MTk0OTI3OX0.O28U1iELnBuq7B_vjlanLJVkNmAgrjpt2yNHXg2HDeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);